"""add notion id into event table

Revision ID: 28534122dae9
Revises: e41de58a4ef4
Create Date: 2026-01-22 21:08:55.890309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28534122dae9'
down_revision: Union[str, Sequence[str], None] = 'e41de58a4ef4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('notion_id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'notion_id')
    # ### end Alembic commands ###
