"""add time columns into user table

Revision ID: 36079a99206a
Revises: 198450619f82
Create Date: 2026-01-20 15:58:22.951574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36079a99206a'
down_revision: Union[str, Sequence[str], None] = '198450619f82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.Enum('WRITING', 'UPDATE_NEEDED', 'UPDATING', 'SYNCED', 'INVITED', 'DELETE', 'DELETED', name='userstatus', native_enum=False), nullable=False))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('users', 'phone',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'discord_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'notion_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'notion_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'discord_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'phone',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'status')
    # ### end Alembic commands ###
