"""add env variable initialzing

Revision ID: 40b0325eca15
Revises: e9adfb10f828
Create Date: 2026-01-20 22:09:59.565259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b0325eca15'
down_revision: Union[str, Sequence[str], None] = 'e9adfb10f828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'system_settings', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'system_settings', type_='unique')
    # ### end Alembic commands ###
