"""change id column types

Revision ID: 489faa729989
Revises: 28534122dae9
Create Date: 2026-01-22 21:51:03.193342

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '489faa729989'
down_revision: Union[str, Sequence[str], None] = '28534122dae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'notion_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.add_column('groups', sa.Column('category_id', sa.BigInteger(), nullable=False))
    op.alter_column('groups', 'notion_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('groups', 'discord_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.create_unique_constraint(None, 'groups', ['category_id'])
    op.alter_column('users', 'discord_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('users', 'notion_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'notion_id',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('users', 'discord_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_constraint(None, 'groups', type_='unique')
    op.alter_column('groups', 'discord_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('groups', 'notion_id',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('groups', 'category_id')
    op.alter_column('events', 'notion_id',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
