"""fix group and event table

Revision ID: bb6f6ac9faef
Revises: 39f20c9be8ae
Create Date: 2026-01-20 16:31:47.560996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb6f6ac9faef'
down_revision: Union[str, Sequence[str], None] = '39f20c9be8ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('start_time', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('ststus', sa.Enum('WRITING', 'UPDATE_NEEDED', 'UPDATING', 'SYNCED', 'DELETE', 'DELETED', name='eventstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=30), nullable=False),
    sa.Column('color', sa.Enum('BASIC', 'GREY', 'BROWN', 'ORANGE', 'YELLOW', 'GREEN', 'BLUE', 'PURPLE', 'PINK', 'RED', name='color', native_enum=False), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('ststus', sa.Enum('WRITING', 'UPDATE_NEEDED', 'UPDATING', 'SYNCED', 'DELETE', 'DELETED', name='groupstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('discord_id', sa.Integer(), nullable=True),
    sa.Column('notion_id', sa.Integer(), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('WRITING', 'UPDATE_NEEDED', 'UPDATING', 'SYNCED', 'INVITED', 'DELETE', 'DELETED', name='userstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('discord_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('notion_id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('groups')
    op.drop_table('events')
    # ### end Alembic commands ###
