"""add notion/discord id into group table

Revision ID: e41de58a4ef4
Revises: 40b0325eca15
Create Date: 2026-01-22 21:07:31.665179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e41de58a4ef4'
down_revision: Union[str, Sequence[str], None] = '40b0325eca15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('notion_id', sa.Integer(), nullable=False))
    op.add_column('groups', sa.Column('discord_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'groups', ['discord_id'])
    op.create_unique_constraint(None, 'groups', ['notion_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groups', type_='unique')
    op.drop_constraint(None, 'groups', type_='unique')
    op.drop_column('groups', 'discord_id')
    op.drop_column('groups', 'notion_id')
    # ### end Alembic commands ###
